name = "H4-HartZFear-Modpack"
author = "Okan Celik"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05754de93da977e49e0f78457b408b953f94ce8de85fa54604a2779ad4a81cef"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
