name = "H4-HartZFear-Modpack"
author = "Okan Celik"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f0faa3daa5b50ac764f3201f729041b5c9a4748d51bca6d50ab4b3db0be94c7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
