name = "H4-HartZFear-Modpack"
author = "Okan Celik"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "972dcca3dbd47005ea67b3f53424062d0e16d1e0419cbc0c3c508e51a0d240c8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
