name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packwiz
        run: |
          curl -o packwiz.zip -L https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz.zip
          chmod +x packwiz
          rm packwiz.zip

      - name: Build
        run: |
          ./packwiz curseforge export
          mkdir rel
          cp *.zip rel/
          cp pack.toml rel/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Curseforge
          path: |
            "*.zip"
            pack.toml

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1
        if: github.event_name == 'release'
        env:
          GHR_PATH: rel
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
